import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {packSpatialDelivery} from '../scripts/pack-spatial-delivery.mjs';
import {loadSpatial} from '../site/spatial.js';
import {SPATIAL_MODEL} from '../site/spatial-model.js';

test('lazy delivery preserves prefecture splits, island scope and GeoJSON without eager overviews',async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'spider-delivery-')),originalFetch=globalThis.fetch;
  t.after(async()=>{globalThis.fetch=originalFetch;await fs.rm(root,{recursive:true,force:true});});
  const write=(name,value)=>fs.writeFile(path.join(root,name),typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value));
  const hash=x=>createHash('sha256').update(x).digest('hex');
  const pack=async(prefix,value)=>{const raw=Buffer.from(JSON.stringify(value)),packed=gzipSync(raw),sha256=hash(packed),file=prefix+'-'+sha256.slice(0,12)+'.json.gz';await write(file,packed);return {file,sha256,bytes:packed.length,decodedBytes:raw.length,cells:value.cells.length};};
  const flat=[320,3],cells=[[10000,15000,1,flat],[10000,15000,2,[320,5]]],id='hokkaido-156-234';
  const tile={...await pack(id,{schema:5,step:1,cells}),id,bounds:[10000,15000,10001,15001],prefs:[1,2]};
  const overview=await pack('overview',{schema:5,step:64,cells});
  const manifest={schema:5,model:SPATIAL_MODEL,tiles:[tile],overview};await write('manifest.json',manifest);
  const sourceManifestSHA256=hash(await fs.readFile(path.join(root,'manifest.json')));
  const summary=Object.fromEntries(Array.from({length:47},(_,i)=>[i+1,{areas:{320:i===0?3:5},meshes:1}]));
  const rule={id:'H001',label:'森林',baseClasses:[5],classes:[5],elevation:[0,1,2,3],supported:true,edge:false,rice:false,river:false,vegetation:0,coast:false,water:false,built:false,pending:[],limitations:[]};
  await write('summary.json',{schema:5,model:SPATIAL_MODEL,localOnly:true,summary,rules:{1:[rule]}});
  const regions={1:{pref:1,areas:{320:3},meshes:1,bounds:[131,31,132,32],names:['島A']},2:{pref:2,areas:{320:5},meshes:1,bounds:[131,31,132,32],names:['本土']}};
  const g={schema:1,sourceManifestSHA256,regions,tiles:{[id]:[[0,1],[1,2]]},mainland:{2:'2'},islands:{島A:'1'},overview:cells.map((r,i)=>[...r,i+1])};
  const packed=gzipSync(Buffer.from(JSON.stringify(g)));await write('geography.json.gz',packed);await write('geography-manifest.json',{schema:1,sha256:hash(packed)});
  packSpatialDelivery(root);
  const requests=[];globalThis.fetch=async url=>{requests.push(String(url));try{return new Response(await fs.readFile(path.join(root,path.basename(String(url)))));}catch{return new Response('',{status:404});}};
  const spatial=await loadSpatial();assert.ok(!requests.some(x=>/map-(?:pref|region)-|overview-/.test(x)));
  const species={id:'1',classes:[5],records:{1:1},recordAreas:{1:{mainland:false,islands:['島A'],unspecified:false}}};
  const options={bounds:{west:130,east:133,south:30,north:33},prefs:[1,2],species,settings:{scope:'environment',model:'distance',distance:500},signal:new AbortController().signal};
  const coarse=await spatial.mapCells({...options,zoom:5});assert.equal(coarse.cells.length,1);assert.equal(coarse.cells[0].matching,8);assert.deepEqual(coarse.cells[0].prefs,[1,2]);
  const detail=await spatial.mapCells({...options,zoom:12});assert.equal(detail.cells[0].matching,8);assert.equal(detail.step,.25);
  const island=await spatial.mapCells({...options,prefs:[1],zoom:5,settings:{...options.settings,scope:'recorded'}});assert.equal(island.cells[0].matching,3);assert.ok(requests.some(x=>/map-region-1-/.test(x)));assert.ok(!requests.some(x=>/map-pref-3-/.test(x)));
  const geo=await spatial.exportGeoJSON({...options,catalog:{prefectures:['A','B']},onProgress:()=>{}});assert.equal(geo.features.length,2);assert.deepEqual(geo.features.map(f=>f.properties.prefecture),['A','B']);
  const off={...options,settings:{...options.settings,excludedClasses:[5]}};
  assert.equal((await spatial.mapCells({...off,zoom:12})).cells[0].matching,0);
  const filteredGeo=await spatial.exportGeoJSON({...off,catalog:{prefectures:['A','B']},onProgress:()=>{}});assert.equal(filteredGeo.features.length,0);assert.deepEqual(filteredGeo.metadata.excluded_landcover_classes,[5]);
  const cancelled=new AbortController();cancelled.abort();await assert.rejects(spatial.mapCells({...options,zoom:5,signal:cancelled.signal}),{name:'AbortError'});
});
